apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpod
  name: alpod
spec:
  containers:
  - image: alpine
    name: alpod
    command: ["/bin/sh","-c","ping google.com"]  #  replacing  default parent process in pod if it was created by Entrypoint
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
