apiVersion: v1
kind: Pod
metadata:   #  info about whatever we want to deploy
  creationTimestamp: null
  labels:   #  tag  given to a pod that is must 
   run: ashuwebpod1  #  key : value pair  format data called label 
  name: ashuwebpod1  # name of pod 
spec:
  containers:
  - image: nginx  # docker image 
    name: ashuwebpod1  #  name of container 
    ports:
    - containerPort: 80  #  this will be same as application port configured in Dockerfile under expose keyword
    resources: {}   #  we can limit resources to pod
  dnsPolicy: ClusterFirst
  restartPolicy: Always    # if nodes goes down and come up again the pod will be restarted 
status: {}

---
apiVersion: v1
kind: Service  #  we are requesting  for  service deployment 
metadata:
  creationTimestamp: null 
  labels:   #  label of  service  as of now  there is no use of service label 
    app: ashus1  #  this entire label part can be ignored 
  name: ashus1  #  name  of service 
spec:
  ports:
  - name: myport
    port: 1111   # port  that will be bounded with service  IP 
    protocol: TCP   #  optional field 
    targetPort: 80   #  on what port number service  will forward  traffic  to pod 
  selector:  #  this is for searching  pod on behalf of labels
   run: ashuwebpod1  #  this is the label of pod where app is running 
  type: NodePort   #  type  of Service  we  want to create 
