FROM   alpine
#  base docker  image and it will pulled  from docker hub if not present 
MAINTAINER   ashutoshh@linux.com , 9509957594  
#  image  designer  information 
#   maintainer is an optional keyword
CMD  ping  fb.com 
#  now  my new image  is  going to have  this as default parent process
#   for a container  the parent process can be only one  rest will be child process
