apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podx1
  name: podx1
spec:
  containers:
  - image: dockerashu/ciscohttpd:june2020v1
    name: podx1
    env:
    - name: x
      value: "2"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
